### PR TITLE
Fix #1107?

### LINKED ISSUE #1107: [Bug] YouTube app timing out (/crashing) on Startup after closing with pending download
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Tested with AltStore and Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.14.1-3.0 / v18.15.1-3.0

### Describe the bug

Upon starting the YouTube app from Homescreen, the app simply shows the YT logo for an extended period of time until it eventually times out and therefore crashes. 

### Steps to reproduce the issue

1. Sideload the Youtube app
2. Open the App
3. Observe

### Crash log (if the app crashes)

```shell
{"app_name":"YouTube","timestamp":"2023-04-29 22:00:12.00 +0200","app_version":"18.14.1","slice_uuid":"0b9c899e-e1f4-3b56-86d8-735badbce776","build_version":"18.14.1","platform":2,"bundleID":"com.google.ios.youtube.RT5J7FJK8H","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.4 (20E247)","roots_installed":0,"name":"YouTube","incident_id":"06463E19-E3A6-40A4-84B5-A899BE5FD881"}
{
  "uptime" : 4100,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone14,5",
  "coalitionID" : 509,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.4",
    "releaseType" : "User",
    "build" : "20E247"
  },
  "captureTime" : "2023-04-29 22:00:12.2976 +0200",
  "incident" : "06463E19-E3A6-40A4-84B5-A899BE5FD881",
  "pid" : 1097,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-04-29 21:59:51.2895 +0200",
  "procStartAbsTime" : 99094073210,
  "procExitAbsTime" : 99598255867,
  "procName" : "YouTube",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"18.14.1","CFBundleVersion":"18.14.1","CFBundleIdentifier":"com.google.ios.youtube.RT5J7FJK8H","DTAppStoreToolsBuild":"14E221"},
  "storeInfo" : {"deviceIdentifierForVendor":"5B49F42E-309F-429F-B7E4-A16EB64CDCE8","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube.RT5J7FJK8H",
  "crashReporterKey" : "a938166b7b420b83b360604b7d77d4b4619d9766",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "throttleTimeout" : 2147483647,
  "codeSigningID" : "com.google.ios.youtube.RT5J7FJK8H",
  "codeSigningTeamID" : "RT5J7FJK8H",
  "codeSigningFlags" : 570434309,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 0,
  "basebandVersion" : "2.55.00",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL"},
  "termination" : {"code":2343432205,"flags":6,"namespace":"FRONTBOARD","reasons":["<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:process-launch watchdog transgression: application<com.google.ios.youtube.RT5J7FJK8H>:1097 exhausted real (wall clock) time allowance of 20.00 seconds","ProcessVisibility: Foreground","ProcessState: Running","WatchdogEvent: process-launch","WatchdogVisibility: Foreground","WatchdogCPUStatistics: (","\"Elapsed total CPU time (seconds): 11.400 (user 7.110, system 4.290), 9% CPU\",","\"Elapsed application CPU time (seconds): 0.588, 0% CPU\"",") reportType:CrashLog maxTerminationResistance:Interactive>"]},
  "ktriageinfo" : "VM - (arg = 0x0) pmap_enter retried due to resource shortage\n",
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":43402,"threadState":{"x":[{"value":18446744073709551612},{"value":0},{"value":5637},{"value":0},{"value":8116896144,"symbolLocation":40,"symbol":"_OS_dispatch_source_vtable"},{"value":0},{"value":0},{"value":35},{"value":5895},{"value":5636},{"value":8245926024},{"value":15},{"value":11048348},{"value":0},{"value":216172790231176201,"symbolLocation":216172782113783809,"symbol":"OBJC_CLASS_$__UIApplicationConfigurationLoader"},{"value":8117392392,"symbolLocation":0,"symbol":"OBJC_CLASS_$__UIApplicationConfigurationLoader"},{"value":515},{"value":6705412896,"symbolLocation":0,"symbol":"__63-[_UIApplicationConfigurationLoader _loadInitializationContext]_block_invoke"},{"value":0},{"value":5637},{"value":0},{"value":8117402072,"symbolLocation":0,"symbol":"_loadInitializationContext.load_once"},{"value":16777218},{"value":12773192216511095304},{"value":8117392360,"symbolLocation":8,"symbol":"OBJC_CLASS_$_UIScreen"},{"value":8116885124,"symbolLocation":0,"symbol":"runtimeLock"},{"value":8116912672,"symbolLocation":224,"symbol":"_main_thread"},{"value":8116989464,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSString"},{"value":9507736622016304656}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6788622492},"cpsr":{"value":4096},"fp":{"value":6168413424},"sp":{"value":6168413392},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7719987132,"matchesCrashFrame":1},"far":{"value":8162179800}},"queue":"com.apple.main-thread","frames":[{"imageOffset":6076,"symbol":"__ulock_wait","symbolLocation":8,"imageIndex":15},{"imageOffset":18588,"symbol":"_dlock_wait","symbolLocation":56,"imageIndex":16},{"imageOffset":18380,"symbol":"_dispatch_once_wait","symbolLocation":112,"imageIndex":16},{"imageOffset":1528456,"symbol":"-[_UIApplicationConfigurationLoader _loadInitializationContext]","symbolLocation":152,"imageIndex":17},{"imageOffset":1526204,"symbol":"-[_UIApplicationConfigurationLoader applicationInitializationContext]","symbolLocation":24,"imageIndex":17},{"imageOffset":2134732,"symbol":"-[_UIScreenInitialDisplayConfigurationLoader initialDisplayContext]","symbolLocation":120,"imageIndex":17},{"imageOffset":2134364,"symbol":"+[UIScreen initialize]","symbolLocation":116,"imageIndex":17},{"imageOffset":88056,"symbol":"CALLING_SOME_+initialize_METHOD","symbolLocation":24,"imageIndex":18},{"imageOffset":44332,"symbol":"initializeNonMetaClass","symbolLocation":904,"imageIndex":18},{"imageOffset":146860,"symbol":"initializeAndMaybeRelock(objc_class*, objc_object*, locker_mixin<lockdebug::lock_mixin<objc_lock_base_t>>&, bool)","symbolLocation":156,"imageIndex":18},{"imageOffset":34660,"symbol":"lookUpImpOrForward","symbolLocation":912,"imageIndex":18},{"imageOffset":11460,"symbol":"_objc_msgSend_uncached","symbolLocation":68,"imageIndex":18},{"imageOffset":18709908,"imageIndex":4},{"imageOffset":18709160,"imageIndex":4},{"imageOffset":18693456,"imageIndex":4},{"imageOffset":18693176,"imageIndex":4},{"imageOffset":19385020,"imageIndex":4},{"imageOffset":19384948,"imageIndex":4},{"imageOffset":302172,"symbol":"_decodeObjectBinary","symbolLocation":2436,"imageIndex":19},{"imageOffset":134736,"symbol":"_decodeObject","symbolLocation":256,"imageIndex":19},{"imageOffset":312404,"symbol":"-[NSKeyedUnarchiver decodeObjectForKey:]","symbolLocation":216,"imageIndex":19},{"imageOffset":19432960,"imageIndex":4},{"imageOffset":302172,"symbol":"_decodeObjectBinary","symbolLocation":2436,"imageIndex":19},{"imageOffset":134736,"symbol":"_decodeObject","symbolLocation":256,"imageIndex":19},{"imageOffset":312404,"symbol":"-[NSKeyedUnarchiver decodeObjectForKey:]","symbolLocation":216,"imageIndex":19},{"imageOffset":783036,"symbol":"+[NSKeyedUnarchiver unarchiveObjectWithData:]","symbolLocation":68,"imageIndex":19},{"imageOffset":19416836,"imageIndex":4},{"imageOffset":19387760,"imageIndex":4},{"imageOffset":19387632,"imageIndex":4},{"imageOffset":16044,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":16},{"imageOffset":22252,"symbol":"_dispatch_once_callout","symbolLocation":32,"imageIndex":16},{"imageOffset":19387612,"imageIndex":4},{"imageOffset":19387484,"imageIndex":4},{"imageOffset":71140,"symbol":"load_images","symbolLocation":824,"imageIndex":18},{"imageOffset":21308,"symbol":"dyld4::RuntimeState::notifyObjCInit(dyld4::Loader const*)","symbolLocation":164,"imageIndex":20},{"imageOffset":36160,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":208,"imageIndex":20},{"imageOffset":180824,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const","symbolLocation":112,"imageIndex":20},{"imageOffset":59040,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const","symbolLocation":304,"imageIndex":20},{"imageOffset":33892,"symbol":"dyld4::APIs::dlopen_from(char const*, int, void*)","symbolLocation":1440,"imageIndex":20},{"imageOffset":32672,"imageIndex":3},{"imageOffset":180684,"symbol":"invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const","symbolLocation":168,"imageIndex":20},{"imageOffset":387824,"symbol":"invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":172,"imageIndex":20},{"imageOffset":22688,"symbol":"invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":528,"imageIndex":20},{"imageOffset":19480,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":296,"imageIndex":20},{"imageOffset":16816,"symbol":"dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":192,"imageIndex":20},{"imageOffset":358620,"symbol":"dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":160,"imageIndex":20},{"imageOffset":65724,"symbol":"dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":432,"imageIndex":20},{"imageOffset":51416,"symbol":"dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const","symbolLocation":448,"imageIndex":20},{"imageOffset":36172,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":220,"imageIndex":20},{"imageOffset":36136,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":184,"imageIndex":20},{"imageOffset":180824,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const","symbolLocation":112,"imageIndex":20},{"imageOffset":59040,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const","symbolLocation":304,"imageIndex":20},{"imageOffset":279108,"symbol":"dyld4::APIs::runAllInitializersForMain()","symbolLocation":340,"imageIndex":20},{"imageOffset":98364,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3404,"imageIndex":20},{"imageOffset":89308,"symbol":"start","symbolLocation":1948,"imageIndex":20}]},{"id":43433,"queue":"com.apple.uikit.applicationSupportClient","frames":[{"imageOffset":6076,"symbol":"__ulock_wait","symbolLocation":8,"imageIndex":15},{"imageOffset":4112,"symbol":"_os_unfair_lock_lock_slow","symbolLocation":176,"imageIndex":21},{"imageOffset":32876,"symbol":"dyld4::APIs::dlopen_from(char const*, int, void*)","symbolLocation":424,"imageIndex":20},{"imageOffset":89424,"symbol":"imp_implementationWithBlock","symbolLocation":68,"imageIndex":18},{"imageOffset":130352,"symbol":"+[BSXPCServiceConnectionProxy proxyForConnection:handshake:withProtocol:activeXPCConnection:xpcConnectionTargetQueue:replyQueue:target:attributes:assertionProvider:]","symbolLocation":832,"imageIndex":22},{"imageOffset":162240,"symbol":"-[BSXPCServiceConnectionEventHandler remoteTargetWithHandshake:assertionAttributes:]","symbolLocation":288,"imageIndex":22},{"imageOffset":8252,"symbol":"-[BSXPCServiceConnection remoteTargetWithAssertionAttributes:enforcingLaunchConstraints:]","symbolLocation":428,"imageIndex":22},{"imageOffset":9240,"symbol":"__44-[UISApplicationSupportClient _remoteTarget]_block_invoke","symbolLocation":316,"imageIndex":23},{"imageOffset":16044,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":16},{"imageOffset":78888,"symbol":"_dispatch_lane_barrier_sync_invoke_and_complete","symbolLocation":56,"imageIndex":16},{"imageOffset":11540,"symbol":"-[UISApplicationSupportClient _remoteTarget]","symbolLocation":184,"imageIndex":23},{"imageOffset":11112,"symbol":"-[UISApplicationSupportClient applicationInitializationContextWithParameters:]","symbolLocation":164,"imageIndex":23},{"imageOffset":3788320,"symbol":"__63-[_UIApplicationConfigurationLoader _loadInitializationContext]_block_invoke_2","symbolLocation":172,"imageIndex":17},{"imageOffset":4746952,"symbol":"__UIAPPLICATION_IS_LOADING_INITIALIZATION_INFO_FROM_THE_SYSTEM__","symbolLocation":28,"imageIndex":17},{"imageOffset":5245828,"symbol":"__63-[_UIApplicationConfigurationLoader _loadInitializationContext]_block_invoke","symbolLocation":100,"imageIndex":17},{"imageOffset":16044,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":16},{"imageOffset":22252,"symbol":"_dispatch_once_callout","symbolLocation":32,"imageIndex":16},{"imageOffset":1528456,"symbol":"-[_UIApplicationConfigurationLoader _loadInitializationContext]","symbolLocation":152,"imageIndex":17},{"imageOffset":3999888,"symbol":"__70-[_UIApplicationConfigurationLoader startPreloadInitializationContext]_block_invoke","symbolLocation":20,"imageIndex":17},{"imageOffset":8992,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":16},{"imageOffset":16044,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":16},{"imageOffset":88676,"symbol":"_dispatch_root_queue_drain","symbolLocation":684,"imageIndex":16},{"imageOffset":90456,"symbol":"_dispatch_worker_thread2","symbolLocation":164,"imageIndex":16},{"imageOffset":3488,"symbol":"_pthread_wqthread","symbolLocation":228,"imageIndex":24},{"imageOffset":2940,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":24}]},{"id":43437,"frames":[{"imageOffset":2932,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":24}]},{"id":43439,"queue":"BSXPCCnx:com.apple.frontboard.systemappservices","frames":[{"imageOffset":6076,"symbol":"__ulock_wait","symbolLocation":8,"imageIndex":15},{"imageOffset":4112,"symbol":"_os_unfair_lock_lock_slow","symbolLocation":176,"imageIndex":21},{"imageOffset":243608,"symbol":"__55-[BSXPCServiceConnection _lock_activateNowOrWhenReady:]_block_invoke.149","symbolLocation":32,"imageIndex":22},{"imageOffset":29200,"symbol":"-[BSXPCServiceConnection _connection_consumeLock_runPendedEventsIfAppropriate]","symbolLocation":508,"imageIndex":22},{"imageOffset":246136,"symbol":"__55-[BSXPCServiceConnection _lock_activateNowOrWhenReady:]_block_invoke_3","symbolLocation":508,"imageIndex":22},{"imageOffset":30912,"symbol":"__52-[BSXPCServiceConnectionMessage _sendSynchronously:]_block_invoke","symbolLocation":216,"imageIndex":22},{"imageOffset":122596,"symbol":"_xpc_connection_reply_callout","symbolLocation":124,"imageIndex":25},{"imageOffset":69352,"symbol":"_xpc_connection_call_reply_async","symbolLocation":88,"imageIndex":25},{"imageOffset":16172,"symbol":"_dispatch_client_callout3","symbolLocation":20,"imageIndex":16},{"imageOffset":138808,"symbol":"_dispatch_mach_msg_async_reply_invoke","symbolLocation":344,"imageIndex":16},{"imageOffset":46092,"symbol":"_dispatch_lane_serial_drain","symbolLocation":372,"imageIndex":16},{"imageOffset":49368,"symbol":"_dispatch_lane_invoke","symbolLocation":436,"imageIndex":16},{"imageOffset":93404,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":648,"imageIndex":16},{"imageOffset":3548,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":24},{"imageOffset":2940,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":24}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4298424320,
    "size" : 12713984,
    "uuid" : "0b9c899e-e1f4-3b56-86d8-735badbce776",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/YouTube",
    "name" : "YouTube"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4463804416,
    "size" : 111394816,
    "uuid" : "87c2ce9b-6c15-3371-942a-dcafb43120e8",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/Module_Framework.framework\/Module_Framework",
    "name" : "Module_Framework"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4322918400,
    "size" : 1245184,
    "uuid" : "509fdab7-cedf-3fc3-81e1-ccfd6ce62f36",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/widevine_cdm_secured_ios.framework\/widevine_cdm_secured_ios",
    "name" : "widevine_cdm_secured_ios"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4317364224,
    "size" : 98304,
    "uuid" : "5d411b8b-1fe6-3f7e-8cdb-b53978affe93",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/uYouPlus.dylib",
    "name" : "uYouPlus.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4357652480,
    "size" : 27246592,
    "uuid" : "ea0fd39e-5805-300f-aa11-90fa8d202968",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/uYou.dylib",
    "name" : "uYou.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4320886784,
    "size" : 1064960,
    "uuid" : "64b3521d-f3b8-3932-b4d8-e88bfb83955f",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/libFLEX.dylib",
    "name" : "libFLEX.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4317822976,
    "size" : 196608,
    "uuid" : "b93f0193-3c33-36af-9b66-b0ff1e9c7729",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/iSponsorBlock.dylib",
    "name" : "iSponsorBlock.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4317282304,
    "size" : 49152,
    "uuid" : "e5b847a5-3842-3126-9075-ab21154903e8",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/YouPiP.dylib",
    "name" : "YouPiP.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4317675520,
    "size" : 81920,
    "uuid" : "b649036c-b62b-385a-ab77-77ea20e5aa6f",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/YouTubeDislikesReturn.dylib",
    "name" : "YouTubeDislikesReturn.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4317528064,
    "size" : 49152,
    "uuid" : "cc1c3e1b-0def-3cd4-ad55-960cee41d986",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/YTABConfig.dylib",
    "name" : "YTABConfig.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4317609984,
    "size" : 32768,
    "uuid" : "a123324f-8d87-368a-853d-6e1a28ab69a2",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/YTUHD.dylib",
    "name" : "YTUHD.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4319363072,
    "size" : 294912,
    "uuid" : "6eb2aa2b-6a31-3953-8c96-30e617840454",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/Alderis.framework\/Alderis",
    "name" : "Alderis"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4318101504,
    "size" : 32768,
    "uuid" : "f0db669b-0333-39a2-879e-af7a7c622981",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/libcolorpicker.dylib",
    "name" : "libcolorpicker.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4318625792,
    "size" : 98304,
    "uuid" : "ffa3562c-e21d-3fa1-a2df-98d17214503e",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/CF419421-60E3-4D83-BD1E-398E61C0DA61\/YouTube.app\/Frameworks\/CydiaSubstrate.framework\/CydiaSubstrate",
    "name" : "CydiaSubstrate"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4326506496,
    "size" : 376832,
    "uuid" : "998a8b2e-2574-3fee-b779-485324a26d15",
    "path" : "\/private\/preboot\/Cryptexes\/OS\/usr\/lib\/libstdc++.6.0.9.dylib",
    "name" : "libstdc++.6.0.9.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7719981056,
    "size" : 229368,
    "uuid" : "5998c9ae-c77e-3681-bd6c-0883c89297cf",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6788603904,
    "size" : 290816,
    "uuid" : "b74732b5-d7fe-34a4-9346-41945701f020",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6700167168,
    "size" : 25309184,
    "uuid" : "b0858d8e-7220-37bf-873f-ecc2b0a358c3",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6549422080,
    "size" : 278432,
    "uuid" : "95bd232e-3710-30fd-adb1-7956d55de41a",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6568476672,
    "size" : 9297920,
    "uuid" : "35567930-fbc2-374b-b44b-1ddfe3ada4a1",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7191392256,
    "size" : 547108,
    "uuid" : "41605dc7-f412-37d1-b51b-fee1a26701e9",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8269332480,
    "size" : 28656,
    "uuid" : "2e6c66fc-2eb9-34f9-995b-ae0b16e030c4",
    "path" : "\/usr\/lib\/system\/libsystem_platform.dylib",
    "name" : "libsystem_platform.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7036014592,
    "size" : 352256,
    "uuid" : "f2e2a0e8-7f96-30f7-b841-c5bd09d98163",
    "path" : "\/System\/Library\/PrivateFrameworks\/BoardServices.framework\/BoardServices",
    "name" : "BoardServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6887239680,
    "size" : 176128,
    "uuid" : "e069bacf-1216-3fb8-8c06-7ee52c0f3ad1",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitServices.framework\/UIKitServices",
    "name" : "UIKitServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8269950976,
    "size" : 49140,
    "uuid" : "b1ee57e1-4484-3714-ba1a-104330ca10c6",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8270225408,
    "size" : 270336,
    "uuid" : "7afe0aec-5b9f-3e5d-9803-12ca228ad324",
    "path" : "\/usr\/lib\/system\/libxpc.dylib",
    "name" : "libxpc.dylib"
  }
],
  "sharedCache" : {
  "base" : 6548668416,
  "size" : 3010707456,
  "uuid" : "824a122c-0f62-3117-858c-cc038821cb5a"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)\nWritable regions: Total=568.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=568.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                           16K        1 \nCoreAnimation                       16K        1 \nFoundation                         192K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           552.0M       32 \nMALLOC guard page                  128K        8 \nSQLite page cache                  256K        2 \nSTACK GUARD                         64K        4 \nStack                             2640K        4 \nVM_ALLOCATE                        256K        1 \n__AUTH                            2613K      278 \n__AUTH_CONST                      31.9M      741 \n__CTF                               824        1 \n__DATA                            45.4M      752 \n__DATA_CONST                      42.9M      750 \n__DATA_DIRTY                      8367K      681 \n__ETC                              112K        1 \n__FONT_DATA                        2352        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       336.6M       16 \n__OBJC_RO                         79.7M        1 \n__OBJC_RW                         2464K        1 \n__TEXT                           952.5M      770 \ndyld private memory               1680K        4 \nmapped file                       29.4M        4 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              2.0G     4061 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "31af075d46589be915199e149358e84d1c9ca722",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {
        "SIRI_VIDEO_APP_SELECTION" : "63d867d28283bf1629655506"
      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "595d38ea-3211-4d6d-a267-6e13fa65c7de",
      "experimentId" : "641b7ffb89b42413772b9435",
      "deploymentId" : 400000002
    },
    {
      "treatmentId" : "61e265d6-f520-4d3b-bf0a-37a0e7d14223",
      "experimentId" : "61695b64436117010456876f",
      "deploymentId" : 400000041
    }
  ]
}
}
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

I've additionally uploaded the streaming log of a full app start/crash to https://pastebin.com/8XQxeYnE - this makes it more clear that the app times out after some time. Also notable is that there's a web request on startup which fails with code -999, however, I'm not sure where to and if it's relevant.

### PR DESCRIPTION
**Pull request by therealFoxster**

### CODE REVIEW

**Comment by HexCodeFFF** [comment]
Are you sure that commenting out that line doesn't break any uYou features?

**Comment by therealFoxster** [comment]
Yea I added that line a while back to hook into uYou's functions to hide the download button in playlists, but now that the button is hidden in uYou by default I don't think it's needed anymore, unless someone also utilized that to do something with  uYou's functions, which I was unable to find in the code. In any case I'll be testing a build with this new change on my personal device and report back if there's something weird, though that's unlikely.

**Comment by HexCodeFFF** [comment]
out of curiosity, why would you hide the button on playlists? I honestly thought it was a bug that there wasn't an option to download playlists

**Comment by therealFoxster** [comment]
Oh, cause the download button was kind of glitchy in the new UI and also the download playlist function barely worked. See #798

**Comment by HexCodeFFF** [comment]
ah

**Pull request merged**
