### PR TITLE
[Feature Pull-Request] YTShortsProgress Submodule

### PR DESCRIPTION
**Pull request by arichorn**
Shorts/Scrubber Bar should be enabled hopefully

**real commit results: 4 additions & 5 deletions**

```
[.gitmodules]
+ [submodule "Tweaks/YTShortsProgress"]
+                 path = Tweaks/YTShortsProgress
+                 url = https://github.com/PoomSmart/YTShortsProgress.git
```
```
[Tweaks/YTShortsProgress]
Submodule [YTShortsProgress] added at [8ee82b]
```
```
[makefile]
+ Tweaks/YTShortsProgress
```
```
[uYouPlus.xm]
- // Enable Shorts scroll bar - @PoomSmart
- %hook YTReelPlayerViewController
- - (BOOL)shouldAlwaysEnablePlayerBar { return YES; }
- %end
-
```

ignore the 1000+ additions and 1000+ deletions below, there was reason I placed the actual changes above. blame the program I use to edit code. if you don't want to merge it with these results then you can go here and grab the files based off of the commits. https://github.com/arichorn/uYouPlusExtra/tree/patch-2

### CODE REVIEW

**Comment by qnblackcat** [comment]
Enabling the scroll bar in Shorts has been added since the beginning 

https://github.com/qnblackcat/uYouPlus/blob/5d0f4537b9f7853cb3ce366d7a6121bbdbfeb8a1/uYouPlus.xm#L297

**Comment by arichorn** [comment]
Oh, for some reason it’s been broken for me 😅

**Comment by qnblackcat** [comment]
I see. I’ll update the tweak in the next releaae

**Comment by arichorn** [comment]
I’ve been on shorts and the scrollbar just doesn’t show for me on my iPad, Even this pull request wouldn’t of fixed it

**Pull request closed without merging**
