### PR TITLE
Actually remove uYou download button in playlists

### PR DESCRIPTION
**Pull request by therealFoxster**
Previous attempt to remove the button didn't work: https://github.com/qnblackcat/uYouPlus/pull/801#issuecomment-1365700214

### CODE REVIEW

**Comment by qnblackcat** [comment]
Ew. We need a whole new dylib just for hidding that one button? :/

**Comment by qnblackcat** [comment]
I asked PoomSmart for help. I hope he knows what's going on

**Comment by therealFoxster** [comment]
Sounds good!

**Comment by PoomSmart** [comment]
Why don't just:

```
%hook YTPlaylistHeaderViewController

- (void)viewDidLoad {
    %orig;
    self.downloadsButton.hidden = YES;
}

%end
```

**Comment by PoomSmart** [comment]
Also, adding another subproject is unnecessary. You have one more dylib to load in that case.

**Comment by PoomSmart** [comment]
@therealFoxster It is also wise to `dlopen` the `uYou.dylib` in `uYouPlus.xm`'s `%ctor`.

**Comment by therealFoxster** [comment]
> @therealFoxster It is also wise to `dlopen` the `uYou.dylib` in `uYouPlus.xm`'s `%ctor`.
> 
> `dlopen([[NSString stringWithFormat:@"%@/Frameworks/uYou.dylib", [[NSBundle mainBundle] bundlePath]] UTF8String], RTLD_LAZY);`

Thanks a lot. I recognized that uYou.dylib was in Frameworks/ but I had no idea how to get a path to it.

**Pull request closed without merging**
