### PR TITLE
Update buildapp.yml

### PR DESCRIPTION
**Pull request by vkhiep**
downgraded Theos
fix build

### CODE REVIEW

**Comment by Vien78** [comment]
I tried substituting the file buildapp.yml
but still gives the same error:
Error: Process completed with exit code 9.
image_2024-03-09_020301409

**Comment by vkhiep** [comment]
> I tried substituting the file buildapp.yml
> but still gives the same error:
> Error: Process completed with exit code 9.
> image_2024-03-09_020301409

Direct link, file type .ipa not zip

**Comment by Vien78** [comment]
> > I tried substituting the file buildapp.yml
> > but still gives the same error:
> > Error: Process completed with exit code 9.
> > image_2024-03-09_020301409
> 
> Direct link, file type .ipa not zip
I am using an .ipa file from https://armconverter.com/decryptedappstore/us
and the uploaded it on Google Drive
opera_USwNRypz3P

**Comment by vkhiep** [comment]
> > I tried substituting the file buildapp.yml
> > but still gives the same error:
> > Error: Process completed with exit code 9.
> > image_2024-03-09_020301409
> 
> Direct link, file type .ipa not zip I am using an .ipa file from https://armconverter.com/decryptedappstore/us and then uploaded it on Google Drive opera_USwNRypz3P

Direct link dropbox: https://dl.dropboxusercontent.com/scl/fi/z76utpmg8mess834xrqxt/ytb-19.09.4.ipa?rlkey=oakyj3nthodvpf7rfpj3bjffd&dl=0

This link is not a direct download link:
https://drive.google.com/file/d/153qNvCyNySbvXM8lf_eTcM0WS8LF0Iv_/view

**Comment by Captainkyle420** [comment]
Havin the same problem with v19.08.2 - 3.0.3

image

**Pull request closed without merging**
