### PR TITLE
Update OLED Dark mode feature

### PR DESCRIPTION
**Pull request by BandarHL**
well, instead of hooking every view for YouTube to change the colour, you can achieve the same results with less code by hooking the Color palette (YTColorPalette).

### CODE REVIEW

**Comment by qnblackcat** [comment]
This is definitely hundreds of times better than my method, which is inefficient and complicated. After all, I'm just a sideloading enthusiast who wants to share what I have with everyone, not a real developer 😅

Anyway, there are a few sections where the OLED color is not applied. Is it possible to achieve the same result via YTColorPalette?

228A3E54-B30B-400E-B215-452524903E5A
948A58F0-9889-4EEA-9973-863FB4C73CC0
82010484-D86F-4B37-BC80-A6F72706475D
D0EF313B-EBEA-4FB6-90DA-129A278CB3E5
BFC42A36-781A-45D0-AD45-E0702690C209
7D12F81D-A9DA-40B9-9C66-ADEFF5E852DA
DBF830C1-E633-4F69-8633-B63ED3DCA6E4

**Comment by BandarHL** [comment]
Unfortunately, there are some views that don't use YTColorPalette, as you mention, we must change it manually.
IMG_0495

**Comment by qnblackcat** [comment]
Do you think it's possible to enable OLED dark mode without restart the app first?

**Comment by BandarHL** [comment]
I don't know if you noticed, with my solution when the change the appearance in YouTube setting it automatically use OLED color, because we hook the color palette class.
https://user-images.githubusercontent.com/31299470/167592010-338aafa2-9c01-4925-b159-1cb0840ec51d.MOV

**Comment by qnblackcat** [comment]
> And we can send a notification center to update the appearance when user enable/disable OLED feature switch

that awesome. Can you do it? <3

**Comment by BandarHL** [comment]
Well the concept is easy, but first we need to find the key that YouTube use, and that is the difficult part im not going to dissemble the whole 120MB binary to find it, so im looking to find it with another way

**Comment by qnblackcat** [comment]
I updated oled darkmode yesterday, app restart is not needed anymore. Can you take a look at it? :)))

**Comment by BandarHL** [comment]
Does it flip automatically to dark mode when you enable OLED switch?

**Comment by qnblackcat** [comment]
It does not 😅

But at least I don’t need to restart the app after switching between Dark/Light theme

**Comment by BandarHL** [comment]
I already write some codes that change the appearance programmatically, so do want me add it when user enable OLED switch? Or it just useless thing

**Comment by qnblackcat** [comment]
I’d like to try it. Can you open another Pull request 😄

**Comment by BandarHL** [comment]
OK

**Comment by BandarHL** [comment]
@PoomSmart  could you please update YTPageStyleController.h by adding (appThemeSetting, setAppThemeSetting), so i can open the pull request for new codes?

**Comment by PoomSmart** [comment]
@BandarHL Done. Also, you are welcome to create pull requests.

**Comment by BandarHL** [comment]
Update:
So I've been working on this all night, the code that changes the theme is:
```objc
// Settings.xm
YTPageStyleController *pageController = [delegate valueForKey:@"_pageStyleController"];
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:1] forKey:@"page_style"];
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:3] forKey:@"app_theme_setting_v3"];[pageController setAppThemeSetting:3];
[pageController updatePageStyles];
```
```objc
// Tweak.xm
// You need to remove OLED group and make it update in real time
%hook YTColorPalette
- (UIColor *)brandBackgroundSolid {
    if (oled() && self.pageStyle == 1) {
        return oledColor;
    }
        return %orig;
}
- (UIColor *)brandBackgroundPrimary {
    if (oled() && self.pageStyle == 1) {
        return oledColor;
    }
        return %orig;
}
- (UIColor *)brandBackgroundSecondary {
    if (oled() && self.pageStyle == 1) {
        return oledColor;
    }
        return %orig;
}
- (UIColor *)staticBrandBlack {
    if (oled() && self.pageStyle == 1) {
        return oledColor;
    }
        return %orig;
}
- (UIColor *)generalBackgroundA {
    if (oled() && self.pageStyle == 1) {
        return oledColor;
    }
        return %orig;
}
%end

// Account view controller
%hook YTAccountPanelBodyViewController
- (UIColor *)backgroundColor:(NSInteger)pageStyle {
    if (oled() && pageStyle == 1) { 
        return oledColor; 
    }
        return %orig;
}
%end

%hook YTInnerTubeCollectionViewController
- (UIColor *)backgroundColor:(NSInteger)pageStyle {
    if (oled() && pageStyle == 1) { 
        return oledColor; 
    }
        return %orig;
}
%end

// Explore
%hook ASScrollView 
- (void)didMoveToWindow {
    if (oled() && isDarkMode()) {
        self.backgroundColor = oledColor;
        %orig;
    }
}
%end

// SponsorBlock settings
%hook SponsorBlockSettingsController
- (void)viewDidLoad {
    if (oled() && self.traitCollection.userInterfaceStyle == UIUserInterfaceStyleDark) {
        %orig;
        self.tableView.backgroundColor = oledColor;
    } else { 
        return %orig(); 
    }
}
%end

%hook YTWatchMiniBarView 
- (void)setBackgroundColor:(UIColor *)color { 
    if (oled() && isDarkMode()) {
        return %orig([UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.9]);
    }
    return %orig;
}
%end

// Search View
%hook YTSearchBarView 
- (void)setBackgroundColor:(UIColor *)color { 
    if (oled() && isDarkMode()) {
        return %orig (oledColor);
    }
        return %orig;
}
%end

%hook YTSearchBoxView 
- (void)setBackgroundColor:(UIColor *)color { 
    if (oled() && isDarkMode()) {
        return %orig (oledColor);
    }
    return %orig;
}
%end

// Comment view
%hook YTCreateCommentAccessoryView // community reply comment
- (void)setBackgroundColor:(UIColor *)color { 
    if (oled() && isDarkMode()) {
        return %orig (oledColor);
    }
    return %orig;
}
%end

%hook YTCreateCommentTextView
- (void)setBackgroundColor:(UIColor *)color { 
    if (oled() && isDarkMode()) {
        return %orig (oledColor);
    }
    return %orig;
}
- (void)setTextColor:(UIColor *)color { // fix black text in #Shorts video's comment
    if (oled() && isDarkMode()) { 
        return %orig ([UIColor whiteColor]); 
    }
    return %orig;
}
%end

%hook YCHLiveChatActionPanelView  // live chat comment
- (void)setBackgroundColor:(UIColor *)color {
    if (oled() && isDarkMode()) {
        return %orig (oledColor);
    }
    return %orig;
}
%end

%hook YTEmojiTextView // live chat comment
- (void)setBackgroundColor:(UIColor *)color {
    if (oled() && isDarkMode()) {
        return %orig (oledColor);
    }
    return %orig;
}
%end

// Separation lines
%hook YTCollectionSeparatorView
- (void)didMoveToWindow {
    if (oled() && isDarkMode()) {}
    else { 
        return %orig(); 
    }
}
%end

// Open link with...
%hook ASWAppSwitchingSheetHeaderView
- (void)setBackgroundColor:(UIColor *)color {
    if (oled() && isDarkMode()) {
        return %orig (oledColor);
    }
}
%end

%hook ASWAppSwitchingSheetFooterView
- (void)setBackgroundColor:(UIColor *)color {
    if (oled() && isDarkMode()) {
        return %orig (oledColor);
    }
}
%end

// this sucks :/
%hook UIView
- (void)setBackgroundColor:(UIColor *)color {
    if (oled() && isDarkMode()) {
        if ([self.nextResponder isKindOfClass:%c(YTHUDMessageView)]) { color = oledColor; }
        if ([self.nextResponder isKindOfClass:%c(ASWAppSwitcherCollectionViewCell)]) { color = oledColor; } // Open link with...
        %orig;
    }
        return %orig;
}
%end
```
The problem is if there any View controller load it before, it will not change to OLED colour it just flips to old dark mode, so it requires to restart the app.

And if you think there is a bug in changing theme code, there is the same result when changing it from YouTube settings.
In this video, I just keep the OLED hooking in runtime so when you enable the switch and you go to enable Dark mode from YouTube settings you get OLED colour without restarting the app, but as I said some view controllers won't change to the new OLED colour unless you restart the app, like Home view controller.

https://user-images.githubusercontent.com/31299470/168238160-bbce2fe5-eb13-447c-8242-0186075e4ee2.mp4

**Comment by qnblackcat** [comment]
I got this error when trying to compile :(

```
nguyendat@ uYouPlus-Tweak % make do
> Making all for tweak uYouPlus…
==> Preprocessing Settings.xm…
==> Compiling Settings.xm (arm64)…
Settings.xm:22:42: error: use of undeclared identifier 'delegate'; did you mean 'delete'?
YTPageStyleController *pageController = [delegate valueForKey:@"_pageStyleController"];
                                         ^~~~~~~~
                                         delete
Settings.xm:22:51: error: use of undeclared identifier 'valueForKey'
YTPageStyleController *pageController = [delegate valueForKey:@"_pageStyleController"];
                                                  ^
Settings.xm:23:2: error: missing '[' at start of message send expression
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:1] forKey:@"page_style"];
 ^
 [
Settings.xm:23:98: error: expected ']'
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:1] forKey:@"page_style"];
                                                                                                 ^
Settings.xm:23:1: note: to match this '['
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:1] forKey:@"page_style"];
^
Settings.xm:23:1: error: expected unqualified-id
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:1] forKey:@"page_style"];
^
Settings.xm:24:2: error: missing '[' at start of message send expression
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:3] forKey:@"app_theme_setting_v3"];
 ^
 [
Settings.xm:24:108: error: expected ']'
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:3] forKey:@"app_theme_setting_v3"];
                                                                                                           ^
Settings.xm:24:1: note: to match this '['
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:3] forKey:@"app_theme_setting_v3"];
^
Settings.xm:24:1: error: expected unqualified-id
[[NSUserDefaults standardUserDefaults] setObject:[NSNumber numberWithInt:3] forKey:@"app_theme_setting_v3"];
^
Settings.xm:25:2: error: missing '[' at start of message send expression
[pageController setAppThemeSetting:3];
 ^
 [
Settings.xm:25:38: error: expected ']'
[pageController setAppThemeSetting:3];
                                     ^
Settings.xm:25:1: note: to match this '['
[pageController setAppThemeSetting:3];
^
Settings.xm:25:1: error: expected unqualified-id
[pageController setAppThemeSetting:3];
^
Settings.xm:26:2: error: missing '[' at start of message send expression
[pageController updatePageStyles];
 ^
 [
Settings.xm:26:17: error: no visible @interface for 'YTPageStyleController' declares the selector 'updatePageStyles'
[pageController updatePageStyles];
 ~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~
Settings.xm:26:1: error: expected unqualified-id
[pageController updatePageStyles];
^
14 errors generated.
make[3]: *** [/Users/nguyendat/theos/makefiles/instance/rules.mk:270: /Users/nguyendat/uYouPlus-Tweak/.theos/obj/debug/arm64/Settings.xm.3500bada.o] Error 1
make[2]: *** [/Users/nguyendat/theos/makefiles/instance/library.mk:52: /Users/nguyendat/uYouPlus-Tweak/.theos/obj/debug/arm64/uYouPlus.dylib] Error 2
make[1]: *** [/Users/nguyendat/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/Users/nguyendat/theos/makefiles/master/rules.mk:117: uYouPlus.all.tweak.variables] Error 2
nguyendat@ uYouPlus-Tweak % 
```

**Comment by PoomSmart** [comment]
All those hooks into `-set(...)Color:`, can they instead be `-didMoveToWindow` ?

**Comment by qnblackcat** [comment]
@PoomSmart I guess they can. Which one is the better?

**Comment by qnblackcat** [comment]
@PoomSmart `didMoveToWindow` is not working properly in some sections. I have to use `layoutSubviews` in that cases. I think using `-set(...)Color:` is still better than `layoutSubviews`?

**Comment by PoomSmart** [comment]
@qnblackcat Actually yeah. Sticking with what it currently is is fine.

**Pull request merged**
