### PR TITLE
iOS 16 OnboardingKit crash fix

### LINKED ISSUE #190: [Bug] App crashes on iOS 16+
### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 
iPhone 8
iOS 16 beta 1
Sideloadly
### Describe the bug
Crashes upon opening

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Open the app

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:
Newly installed app crashes upon opening

### PR DESCRIPTION
**Pull request by level3tjg**
This should fix #190, haven't tested it yet because I don't have a device on iOS 16.

### CODE REVIEW

**Comment by qnblackcat** [comment]
You‘re literally a life saver. I’ll try it out asap

**Comment by asportnoy** [comment]
Thank you for fixing this!

**Comment by arichorn** [comment]
Alright thanks for the fix, I was gonna go back to 15.5 if it was because I thought it was my fault for updating.

**Comment by schweppes-0x** [comment]
Thank you a lot!!

**Comment by arichorn** [comment]
Also here’s the catch about this though. Keep this in mind that iOS 16 is in Beta 1 and it could possibly have changes with this but let’s hope that I’m sure apple won’t modify the developer/sideloading again next beta.

**Pull request merged**
