### PR TITLE
Disable Heatwave in the video player

### PR DESCRIPTION
**Pull request by arichorn**
I have gave out this option for uYouPlus! this should disable the Heatwave in the video player.

### CODE REVIEW

**Comment by qnblackcat** [comment]
Thanks. But Heatwave is a nice feature from YouTube, and it also doesn’t annoying that much. I see no reason why we have to disable the heatwave.

**Comment by arichorn** [comment]
Well. You could make I can turn this into a setting for it since it could be nice for some users whoever doesn’t need it. I’ll modify it

**Comment by arichorn** [comment]
I added back code "clean up", I did a mistaken error that I needed to resolve. but if you still don't want this then at least I tried adding another feature toggle that youtube never adds.

**Comment by qnblackcat** [comment]
I have been trying to keep uYouPlus as simple as possible. Adding unnecessary features isn’t what I want. I’m afraid I have to deny your PR.

**Comment by arichorn** [comment]
alright, I'll close it. cya qnblackcat!

**Pull request closed without merging**
