### PR TITLE
Fix uYou .deb

### LINKED ISSUE #1504: Error while side loading latest build of the .ipa using sideloadly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 18 dev beta 2
- Device model: iPhone 12 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Sideloadly 

### Describe the issue

I built the .ipa from the latest commit, but sideloadly gives me error which is posted below:
ERROR: Guru Meditation 7c026a@447:14dd8f ('expected 1, found 0', ArrayError('expected 45, found 44', SwitchError('no default case defined')))
Install failed: Guru Meditation 7c026a@447:14dd8f ('expected 1, found 0', ArrayError('expected 45, found 44', SwitchError('no default case defined')))

I tried to google it too. People had issues with some of previous uYouPlus versions and had the same error. I wonder what it could be. Let me know if anyone successfully installed the latest .ipa or resolved this error.

### Steps to reproduce

1. Just try to build and install the latest youtube ipa using sideloadly.

### Crash log

_No response_

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TheKfcBandit**
original was broken
reverted temp fix
fixes #1504, #1507

### CODE REVIEW

**Comment by PoomSmart** [comment]
So anything higher than 19.20.4 won't work when sideloaded?

**Comment by iqbal1992** [comment]
> So anything higher than 19.20.2 won't work when sideloaded?

Well I am right now on 19.22.3 with uyou 3.0.4 and everything works great for me on iPhone 12 pro max and iOS 18. No ads, no blank home page spaces and no missing elements. 

Only issue is when I tried to build the .ipa with last week's commit on youtube 19.24.3, I had the same element missing issue but homepage blank spaces were not there, so that part was good.

**Comment by iqbal1992** [comment]
> > So anything higher than 19.20.2 won't work when sideloaded?
> 
> Well I am right now on 19.22.3 with uyou 3.0.4 and everything works great for me on iPhone 12 pro max and iOS 18. No ads, no blank home page spaces and no missing elements. 
> 
> Only issue is when I tried to build the .ipa with last week's commit on youtube 19.24.3, I had the same element missing issue but homepage blank spaces were not there, so that part was good. 

Update: So with the latest commits made hour ago, I tried to build the ipa with 19.25.4 with uyou 3.0.4. Build script was successful but I'm having same issues, UI elements missing and blank spaces at home screen. Then I tried to build the ipa using uyou 3.0.3 and latest youtube and same issues I faced.

**Comment by iqbal1992** [comment]
> where did the uyou deb go?

It was deleted in the latest commit.

**Comment by iqbal1992** [comment]
> I am using v19.26.5 with the 3.0.4 .deb with the latest commits and I am not missing any of the elements that were on that screenshot. I have the casting option and the others that appear to be missing for you. My bottom navigation bar is fine

Where did you download the decrypted ipa of YouTube?

**Comment by iqbal1992** [comment]
> > > I am using v19.26.5 with the 3.0.4 .deb with the latest commits and I am not missing any of the elements that were on that screenshot. I have the casting option and the others that appear to be missing for you. My bottom navigation bar is fine
> 
> > 
> 
> > Where did you download the decrypted ipa of YouTube?
> 
> 
> 
> iPhonecake or armconverter

Can you share decrypted youtube ipa and your built uyouplus ipa ?

**Pull request closed without merging**
