### PR TITLE
Actually remove uYou download button in playlists

### PR DESCRIPTION
**Pull request by therealFoxster**
Thanks @PoomSmart!

### CODE REVIEW

**Comment by PoomSmart** [comment]
Does this approach not work?

https://github.com/qnblackcat/uYouPlus/pull/808#issuecomment-1366327130

**Comment by therealFoxster** [comment]
> Does this approach not work?
> 
> [#808 (comment)](https://github.com/qnblackcat/uYouPlus/pull/808#issuecomment-1366327130)

No, it worked flawlessly. What I meant was I had no idea how to get a path to uYouPlus.dylib until you mentioned it.

**Comment by PoomSmart** [comment]
@therealFoxster Ok, I suggest hooking viewDidLoad method because it's just one method to hook.

**Comment by therealFoxster** [comment]
Not sure why I keep trying to complicate matters. Thanks! I'll open a new pull request.

**Comment by therealFoxster** [comment]
Woah uYou 2.3~1 just came out! We might not need to hide the download button anymore!

**Pull request closed without merging**
