### PR TITLE
Update all Action Dependencies (#765)

### PR DESCRIPTION
**Pull request by arichorn**
Yesterday, I got notified that these were released. So I decided to update them for you if buildapp.yml stopped working in future.
Enjoy qnblackcat! 😉 

Edit: was not only notified. Was also building a tweak until I decided update the dependencies when building

### CODE REVIEW

**Comment by PoomSmart** [comment]
Is it necessary to keep updating dependencies? Can we just update them when either it's needed for new features that uYou+ will use or security vulnerabilities or significant performance improvement?

**Comment by PoomSmart** [comment]
Can this rather be a job of some GitHub bot that monitors the dependencies so human intervention is no longer required?

**Comment by arichorn** [comment]
> Is it necessary to keep updating dependencies? Can we just update them when either it's needed for new features that uYou+ will use or security vulnerabilities or significant performance improvement?

You know this doesn’t need to be merged right now. It’s just gonna be hanging here until qn does need it in the future.

**Comment by yodaluca23** [comment]
> Can this rather be a job of some GitHub bot that monitors the dependencies so human intervention is no longer required?

I'm pretty sure Qn_ does have some sort of automatic bot because, if you notice a lot of dependency updates say "[Auto-Generated]" and it's all automated and is approved soon after whenever Qn_ goes back and manually reviews it...

**Comment by arichorn** [comment]
> I'm pretty sure Qn_ does have some sort of automatic bot because, if you notice a lot of dependency updates say "[Auto-Generated]" and it's all automated and is approved soon after whenever Qn_ goes back and manually reviews it...

Okay to be honest that’s pretty cool, but I only thought it only detected Submodules, didn’t even think it can even do Actions too 👍

**Comment by yodaluca23** [comment]
> > I'm pretty sure Qn_ does have some sort of automatic bot because, if you notice a lot of dependency updates say "[Auto-Generated]" and it's all automated and is approved soon after whenever Qn_ goes back and manually reviews it...
> 
> Okay to be honest that’s pretty cool, but I only thought it only detected Submodules, didn’t even think it can even do Actions too 👍

And if we needed to we could probably get dependabot...

**Comment by arichorn** [comment]
Updated Cache Dependence
3.0.11 >> 3.2.0
to let y’all know

**Comment by qnblackcat** [comment]
As PoomSmart said above, keeping all the dependencies up to date is not really necessary. I will merge this PR, but you don't need to open another PR for this purpose in the future

**Comment by arichorn** [comment]
> As PoomSmart said above, keeping all the dependencies up to date is not really necessary. I will merge this PR, but you don't need to open another PR for this purpose in the future

Sorry. You didn’t really need to merge this though, but anyways this definitely may help buildapp.yml last longer since these usually remove or avoid any upcoming deprecation/deprecated warnings in the future. but I may be wrong so.. 😬✋

**Pull request merged**
