### PR TITLE
Add Portuguese Brazilian translation

### PR DESCRIPTION
**Pull request by VictorxD70**

### CODE REVIEW

**Comment by VictorxD70** [comment]
The correct one is pt-BR, but I based it on an existing language here (zh_tw)

**Comment by qnblackcat** [comment]
>….but I based it on an existing language here (zh_tw)

You should get the language code from here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by VictorxD70** [comment]
This can be just pt, but this language is specific to brazil, the ISO 639-1 of brazilian portuguese language is pt-BR

https://typecraft.org/tc2wiki/Brazilian_Portuguese_(BP)

**Comment by qnblackcat** [comment]
36DBD01A-E20E-4326-BBC5-A531BBEF42FC
Hm. Looks like the YouTube app doens‘t have that language code

**Comment by VictorxD70** [comment]
It has, it's the pt folder, pt is recognized as pt-BR too, you can see there the specific folder for portuguese portugal (pt_PT)

**Comment by VictorxD70** [comment]
I can rename it to pt, so I don't have problems, and stay right with the one on youtube.

**Comment by qnblackcat** [comment]
Got it!

**Pull request merged**
