### PR TITLE
DontEatMyContent Tweak 

### PR DESCRIPTION
**Pull request by arichorn**
I have added this tweak for you qnblackcat! I hope you enjoy!

### CODE REVIEW

**Comment by arichorn** [comment]
No problem!

**Comment by arichorn** [comment]
Also I’m sorry if there were a ton of mistakes in the code, after seeing the changes I realized I implemented this one very poorly except for EN Localization.

**Comment by qnblackcat** [comment]
Nah, it‘s fine

**Comment by arichorn** [comment]
Oh alright 👍

**Pull request merged**
