### PR TITLE
Various fixes + major refactor to increase modularity and maintainability

### PR DESCRIPTION
**Pull request by therealFoxster**
## Changes
- Reorganized project structure and split codebase into multiple files for maintainability
- Reworded various strings to make them more concise
- Updated settings page
- Implemented a few quality-of-life fixes for uYou

### CODE REVIEW

**Comment by PoomSmart** [comment]
Looking good

**Comment by qnblackcat** [comment]
This is neat. It's something I've wanted but never had the time to do

**Comment by RobyRew** [comment]
awesome to see all this work, thank you therealFoxster!

**Comment by jas32096** [comment]
Thank you @therealFoxster for this MR.

I believe it may have broken the ability to go up to 3x speed, with your changes to the uyou speed controls. Ever since updating to this version, I am no longer able to achieve 3x playback and only see the option to go up to 2x

**Comment by qnblackcat** [comment]
> Thank you @therealFoxster for this MR.
> 
> I believe it may have broken the ability to go up to 3x speed, with your changes to the uyou speed controls. Ever since updating to this version, I am no longer able to achieve 3x playback and only see the option to go up to 2x

nope, YouTube uses a new method to display the speed popup. Thus, you can't see the 3x speed anymore. For now, you can go to 3x by using uYou Playback speed controls

**Comment by jas32096** [comment]
> > Thank you @therealFoxster for this MR.
> > I believe it may have broken the ability to go up to 3x speed, with your changes to the uyou speed controls. Ever since updating to this version, I am no longer able to achieve 3x playback and only see the option to go up to 2x
> 
> nope, YouTube uses a new method to display the speed popup. Thus, you can't see the 3x speed anymore. For now, you can go to 3x by using uYou Playback speed controls

I believe I have th
IMG_5A9E20C65D7F-1
at enabled, but still only can go up to 2x. Am I do something wrong?

I have the overlay, but it will not "plus" past "2x". Also, I seem to recall it used to say "1x" for unmodified playback. Now it says "Normal". That's not an issue, only mentioning, if it helps debug.
IMG_AA2924BB671D-1

Thanks for your help.

**Pull request merged**
